Repository apache/calcite, pull requests merged in 2019-07, with the labels that each got.

#1278 [CALCITE-3146] Support the detection of nested aggregations for JdbcAggregate in SqlImplementor
  core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
Labels: returned-with-feedback, tests-missing

#800 [CALCITE-2460][CALCITE-2459] Add implementation of To_Base64 and From_Base64 to SqlFunctions
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java
  site/_docs/reference.md
Labels: LGTM-will-merge-soon, rebase-required

#1298 [CALCITE-3172] RelBuilder#empty does not keep aliases
  core/src/main/java/org/apache/calcite/tools/RelBuilder.java
  core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
Labels: LGTM-will-merge-soon

#1297 [CALCITE-3160] Failed to materialize when the aggregate function uses group key
  core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java
  core/src/test/java/org/apache/calcite/test/MaterializationTest.java
Labels: returned-with-feedback

#1293 [CALCITE-3165] Project#accept(RexShuttle shuttle) does not update rowType
  core/src/main/java/org/apache/calcite/rel/RelNode.java
  core/src/main/java/org/apache/calcite/rel/core/Project.java
  core/src/test/java/org/apache/calcite/test/CalciteSuite.java
  core/src/test/java/org/apache/calcite/test/RexShuttleTest.java
Labels: LGTM-will-merge-soon

#1307 [CALCITE-3182] Trim unused fields for plan of materialized-view before matching.
  core/src/main/java/org/apache/calcite/prepare/CalciteMaterializer.java
  core/src/test/java/org/apache/calcite/test/MaterializationTest.java
Labels: LGTM-will-merge-soon

#1323 [CALCITE-3201] SqlValidator throws exception for sql insert target ta…
  core/src/main/java/org/apache/calcite/schema/ColumnStrategy.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
  core/src/test/java/org/apache/calcite/test/catalog/Fixture.java
  core/src/test/java/org/apache/calcite/test/catalog/MockCatalogReaderExtended.java
  core/src/test/java/org/apache/calcite/test/catalog/VirtualColumnsExpressionFactory.java
  server/src/test/java/org/apache/calcite/test/ServerTest.java
Labels: request review

#1329 [CALCITE-3209] When calling MutableMultiRel::setInput, exception thrown
  core/src/main/java/org/apache/calcite/rel/mutable/MutableMultiRel.java
  core/src/test/java/org/apache/calcite/test/MutableRelTest.java
Labels: LGTM-will-merge-soon

#1269 [CALCITE-3109] Improvements on algebraic operators to express recursive queries (RepeatUnion & TableSpool)
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRepeatUnion.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRepeatUnionRule.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableSpool.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableSpoolRule.java
  core/src/main/java/org/apache/calcite/rel/core/RelFactories.java
  core/src/main/java/org/apache/calcite/rel/core/RepeatUnion.java
  core/src/main/java/org/apache/calcite/rel/core/TableSpool.java
  core/src/main/java/org/apache/calcite/rel/logical/LogicalRepeatUnion.java
  core/src/main/java/org/apache/calcite/rel/logical/LogicalTableSpool.java
  core/src/main/java/org/apache/calcite/tools/RelBuilder.java
  core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionHierarchyTest.java
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Labels: LGTM-will-merge-soon

#1320 [CALCITE-3031] Support for correlated ANY/SOME/ALL sub-query
  core/src/main/java/org/apache/calcite/rel/rules/SubQueryRemoveRule.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
  core/src/test/resources/sql/sub-query.iq
Labels: LGTM-will-merge-soon

#1283 [CALCITE-3153] Improve testing in TpcdsTest using assertEqual instead of printing results
  plus/src/test/java/org/apache/calcite/adapter/tpcds/TpcdsTest.java
Labels: LGTM-will-merge-soon

#1330 [CALCITE-3211] List of MutableRel may fail to be identified by SubstitutionVisitor during matching
  core/src/main/java/org/apache/calcite/rel/mutable/MutableRels.java
  core/src/test/java/org/apache/calcite/test/MutableRelTest.java
Labels: LGTM-will-merge-soon
