Repository apache/calcite, pull requests merged in 2019-12, with the labels that each got.

#1626 [CALCITE-3561] Support using unnest in Interpreter
  core/src/main/java/org/apache/calcite/interpreter/Nodes.java
  core/src/main/java/org/apache/calcite/interpreter/UncollectNode.java
  core/src/test/java/org/apache/calcite/test/InterpreterTest.java
Labels: LGTM-will-merge-soon

#1614 [CALCITE-3546] Improve EnumerableDefaults nested loop join
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Labels: LGTM-will-merge-soon

#1613 [CALCITE-3542] Implement RepeatUnion All=false
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRepeatUnion.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionHierarchyTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionTest.java
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
  site/_docs/algebra.md
Labels: LGTM-will-merge-soon

#1634 [CALCITE-3246] NullPointerException while deserializing udf operator
  core/src/main/java/org/apache/calcite/rel/externalize/RelJson.java
  core/src/main/java/org/apache/calcite/rel/externalize/RelJsonReader.java
  core/src/test/java/org/apache/calcite/plan/RelWriterTest.java
Labels: LGTM-will-merge-soon

#1565 [CALCITE-3481] Support convert TableFunctionScan to SqlNode
  core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
  core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterStructsTest.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Labels: LGTM-will-merge-soon

#1616 [CALCITE-3535] EnumerableJoinRule: remove unnecessary Filter on top of INNER Join
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableJoinRule.java
  core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
  core/src/test/java/org/apache/calcite/test/JdbcFrontJdbcBackLinqMiddleTest.java
  core/src/test/java/org/apache/calcite/test/JdbcTest.java
  core/src/test/java/org/apache/calcite/test/MaterializationTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableHashJoinTest.java
  core/src/test/java/org/apache/calcite/tools/PlannerTest.java
  core/src/test/resources/sql/join.iq
  core/src/test/resources/sql/misc.iq
  core/src/test/resources/sql/some.iq
  core/src/test/resources/sql/sub-query.iq
  linq4j/src/main/java/org/apache/calcite/linq4j/Linq4j.java
  plus/src/test/java/org/apache/calcite/adapter/tpch/TpchTest.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#1651 [CALCITE-3598] EnumerableTableScan: wrong JavaRowFormat for elementType String
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScan.java
  core/src/test/java/org/apache/calcite/test/MaterializationTest.java
Labels: slow-tests-needed

#1699 [CALCITE-3637] Update linq4j tests upgrade from junit4 to junit5
  linq4j/gradle.properties
  linq4j/src/test/java/org/apache/calcite/linq4j/test/JoinPreserveOrderTest.java
  linq4j/src/test/java/org/apache/calcite/linq4j/test/Linq4jSuite.java
  linq4j/src/test/java/org/apache/calcite/linq4j/test/LookupImplTest.java
Labels: LGTM-will-merge-soon
