Repository apache/calcite, pull requests merged in 2019-02, with the labels that each got.

#1023 Add JUnit category for extremely slow tests, launch them in a separate Travis job
  .travis.yml
  core/pom.xml
  core/src/test/java/org/apache/calcite/materialize/LatticeSuggesterTest.java
  core/src/test/java/org/apache/calcite/profile/ProfilerTest.java
  core/src/test/java/org/apache/calcite/test/FoodmartTest.java
  core/src/test/java/org/apache/calcite/test/LatticeTest.java
  core/src/test/java/org/apache/calcite/test/MaterializationTest.java
  core/src/test/java/org/apache/calcite/test/SlowTests.java
  core/src/test/java/org/apache/calcite/util/PartiallyOrderedSetTest.java
Labels: LGTM-will-merge-soon

#898 [CALCITE-2464] Allow to set nullability for columns of structured types (Ruben Quesada Lopez)
  core/src/main/java/org/apache/calcite/jdbc/JavaTypeFactoryImpl.java
  core/src/main/java/org/apache/calcite/rel/type/RelDataTypeFactoryImpl.java
  core/src/main/java/org/apache/calcite/rel/type/RelRecordType.java
  core/src/test/java/org/apache/calcite/sql/type/SqlTypeFactoryTest.java
  core/src/test/java/org/apache/calcite/test/JdbcTest.java
  server/src/main/java/org/apache/calcite/sql/ddl/SqlCreateTable.java
  server/src/test/java/org/apache/calcite/test/ServerTest.java
  server/src/test/resources/sql/type.iq
Labels: LGTM-will-merge-soon, rebase-required

#1059 [CALCITE-2859] Centralize Calcite system properties
  cassandra/src/main/java/org/apache/calcite/adapter/cassandra/CassandraToEnumerableConverter.java
  cassandra/src/test/java/org/apache/calcite/test/CassandraAdapterTest.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableAggregate.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableInterpretable.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableWindow.java
  core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcToEnumerableConverter.java
  core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
  core/src/main/java/org/apache/calcite/interpreter/Interpreter.java
  core/src/main/java/org/apache/calcite/interpreter/JaninoRexCompiler.java
  core/src/main/java/org/apache/calcite/materialize/Lattice.java
  core/src/main/java/org/apache/calcite/plan/RelOptMaterialization.java
  core/src/main/java/org/apache/calcite/plan/RelOptMaterializations.java
  core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
  core/src/main/java/org/apache/calcite/prepare/CalciteMaterializer.java
  core/src/main/java/org/apache/calcite/prepare/CalcitePrepareImpl.java
  core/src/main/java/org/apache/calcite/profile/ProfilerImpl.java
  core/src/main/java/org/apache/calcite/rel/core/Filter.java
  core/src/main/java/org/apache/calcite/rel/logical/LogicalCorrelate.java
  core/src/main/java/org/apache/calcite/rel/metadata/JaninoRelMetadataProvider.java
  core/src/main/java/org/apache/calcite/rel/rules/AggregateStarTableRule.java
  core/src/main/java/org/apache/calcite/rel/rules/MultiJoinOptimizeBushyRule.java
  core/src/main/java/org/apache/calcite/rex/RexExecutorImpl.java
  core/src/main/java/org/apache/calcite/rex/RexLiteral.java
  core/src/main/java/org/apache/calcite/runtime/CalciteException.java
  core/src/main/java/org/apache/calcite/sql/SqlCollation.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlCountAggFunction.java
  core/src/main/java/org/apache/calcite/sql/parser/SqlParserUtil.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidator.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorException.java
  core/src/main/java/org/apache/calcite/tools/Programs.java
  core/src/main/java/org/apache/calcite/util/PartiallyOrderedSet.java
  core/src/main/java/org/apache/calcite/util/SaffronProperties.java
  core/src/main/java/org/apache/calcite/util/Util.java
  core/src/main/java/org/apache/calcite/util/javac/JaninoCompiler.java
  core/src/test/java/org/apache/calcite/jdbc/CalciteRemoteDriverTest.java
  core/src/test/java/org/apache/calcite/plan/volcano/TraitPropagationTest.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/java/org/apache/calcite/test/CalciteAssert.java
  core/src/test/java/org/apache/calcite/test/FoodmartTest.java
  core/src/test/java/org/apache/calcite/test/JdbcTest.java
  core/src/test/java/org/apache/calcite/test/MultiJdbcSchemaJoinTest.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
  core/src/test/java/org/apache/calcite/test/RexProgramTest.java
  core/src/test/java/org/apache/calcite/tools/FrameworksTest.java
  core/src/test/java/org/apache/calcite/tools/PlannerTest.java
  core/src/test/java/org/apache/calcite/util/PartiallyOrderedSetTest.java
  druid/src/main/java/org/apache/calcite/adapter/druid/DruidConnectionImpl.java
  druid/src/test/java/org/apache/calcite/test/DruidAdapterIT.java
  druid/src/test/java/org/apache/calcite/test/DruidAdapterIT2.java
  mongodb/src/main/java/org/apache/calcite/adapter/mongodb/MongoToEnumerableConverter.java
  mongodb/src/test/java/org/apache/calcite/test/MongoAssertions.java
  plus/src/test/java/org/apache/calcite/adapter/tpcds/TpcdsTest.java
  plus/src/test/java/org/apache/calcite/adapter/tpch/TpchTest.java
  plus/src/test/java/org/apache/calcite/materialize/TpcdsLatticeSuggesterTest.java
  spark/src/main/java/org/apache/calcite/adapter/spark/JdbcToSparkConverter.java
  spark/src/main/java/org/apache/calcite/adapter/spark/SparkHandlerImpl.java
  splunk/src/main/java/org/apache/calcite/adapter/splunk/SplunkTableScan.java
  splunk/src/test/java/org/apache/calcite/test/SplunkAdapterTest.java
Labels: LGTM-will-merge-soon

#950 [CALCITE-2703] Reduce code generation and class loading overhead when executing queries in the EnumerableConvention (Stamatis Zampetakis)
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableInterpretable.java
  core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
  linq4j/src/main/java/org/apache/calcite/linq4j/tree/VisitorImpl.java
  ubenchmark/pom.xml
  ubenchmark/src/main/java/org/apache/calcite/adapter/enumerable/CodeGenerationBenchmark.java
  ubenchmark/src/main/java/org/apache/calcite/adapter/enumerable/package-info.java
Labels: LGTM-will-merge-soon, enhancement
