Repository apache/calcite, pull requests merged in 2019-03, with the labels that each got.

#1073 [CALCITE-2338] Make Simplification API more conservative
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdPredicates.java
  core/src/main/java/org/apache/calcite/rex/RexSimplify.java
  core/src/main/java/org/apache/calcite/rex/RexUtil.java
  core/src/main/java/org/apache/calcite/tools/RelBuilder.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon

#1076 [CALCITE-2421] Generalize simplification of self-comparisions
  core/src/main/java/org/apache/calcite/rex/RexSimplify.java
  core/src/test/java/org/apache/calcite/test/RexProgramTest.java
Labels: LGTM-will-merge-soon

#884 [CALCITE-2621] Add rule to execute semi joins with correlation (Ruben Quesada Lopez)
  core/src/main/java/org/apache/calcite/rel/rules/JoinToCorrelateRule.java
  core/src/test/java/org/apache/calcite/rel/rules/SortRemoveRuleTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableCorrelateTest.java
Labels: LGTM-will-merge-soon

#1082 [CALCITE-2890] Elasticsearch adapter. combine "any_value" with other aggs failed
  elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchJson.java
  elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/AggregationTest.java
Labels: LGTM-will-merge-soon

#1084 [CALCITE-2886] Simplification of AND expressions should push negation…
  core/src/main/java/org/apache/calcite/rex/RexSimplify.java
  core/src/main/java/org/apache/calcite/runtime/FlatLists.java
  core/src/test/java/org/apache/calcite/test/MaterializationTest.java
  core/src/test/java/org/apache/calcite/test/RexProgramTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
  core/src/test/resources/sql/blank.iq
  core/src/test/resources/sql/sub-query.iq
Labels: LGTM-will-merge-soon

#1080 [CALCITE-2887] Improve performance of RexLiteral#toJavaString
  core/src/main/java/org/apache/calcite/rex/RexLiteral.java
  core/src/main/java/org/apache/calcite/util/Unsafe.java
  core/src/main/java/org/apache/calcite/util/Util.java
  ubenchmark/src/main/java/org/apache/calcite/benchmarks/StringConstructBenchmark.java
Labels: LGTM-will-merge-soon

#1088 [CALCITE-2895] Add missing arguments to constructor javadoc of LogicAggregate (Chunwei Lei)
  core/src/main/java/org/apache/calcite/rel/logical/LogicalAggregate.java
Labels: LGTM-will-merge-soon

#1077 [CALCITE-2818] EXTRACT returns wrong results for DATE and TIMESTAMP values before epoch
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/resources/sql/misc.iq
Labels: LGTM-will-merge-soon

#923 [CALCITE-2677] Struct types with one field are not mapped correctly to Java Classes (Stamatis Zampetakis)
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableAggregate.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCollect.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScan.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/PhysType.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/PhysTypeImpl.java
  core/src/main/java/org/apache/calcite/jdbc/JavaTypeFactoryImpl.java
  core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
  core/src/main/java/org/apache/calcite/util/Bug.java
  core/src/test/java/org/apache/calcite/adapter/enumerable/PhysTypeTest.java
  core/src/test/java/org/apache/calcite/jdbc/JavaTypeFactoryTest.java
  core/src/test/java/org/apache/calcite/test/JdbcTest.java
  core/src/test/java/org/apache/calcite/test/QuidemTest.java
  core/src/test/resources/sql/struct.iq
Labels: LGTM-will-merge-soon, backward-compatibility

#1095 [CALCITE-2599] add the ASCII function
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  site/_docs/reference.md
Labels: LGTM-will-merge-soon, discussion-in-jira, returned-with-feedback

#1099 [CALCITE-2908] Implement SQL LAST_DAY function
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
  core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/resources/sql/misc.iq
  site/_docs/reference.md
Labels: LGTM-will-merge-soon

#1071 [CALCITE-2877] Make GeodeSchema constructor public to pass client cache object
  geode/src/main/java/org/apache/calcite/adapter/geode/rel/GeodeSchema.java
  geode/src/main/java/org/apache/calcite/adapter/geode/rel/GeodeSchemaFactory.java
  geode/src/main/java/org/apache/calcite/adapter/geode/util/GeodeUtils.java
Labels: LGTM-will-merge-soon, returned-with-feedback

#912 [CALCITE-2729] introducing WindowReduceExpressionsRule
  core/src/main/java/org/apache/calcite/prepare/CalcitePrepareImpl.java
  core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon

#921 [CALCITE-2658] Add ExchangeRemoveConstantKeysRule that removes consta…
  core/src/main/java/org/apache/calcite/prepare/CalcitePrepareImpl.java
  core/src/main/java/org/apache/calcite/rel/rules/ExchangeRemoveConstantKeysRule.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon

#1101 [CALCITE-2909] Optimize Enumerable SemiJoin with lazy computation of innerLookup (Ruben Quesada Lopez)
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Labels: LGTM-will-merge-soon, rebase-required

#1122 [CALCITE-2941] EnumerableLimitRule on Sort with no collation creates EnumerableLimit with wrong traitSet and cluster
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimitRule.java
  core/src/test/java/org/apache/calcite/rel/rules/EnumerableLimitRuleTest.java
Labels: LGTM-will-merge-soon, rebase-required
