Repository apache/calcite, pull requests merged in 2020-09, with the labels that each got.

#2006 [CALCITE-4015] Pass through parent collation request on subset or sup…
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java
  core/src/main/java/org/apache/calcite/rel/RelCollations.java
  core/src/main/java/org/apache/calcite/util/ImmutableIntList.java
  core/src/test/java/org/apache/calcite/rel/RelCollationTest.java
  core/src/test/java/org/apache/calcite/test/TopDownOptTest.java
  core/src/test/resources/org/apache/calcite/test/TopDownOptTest.xml
Labels: LGTM-will-merge-soon

#2126 [CALCITE-4203] RelMdUniqueKeys should not return empty when meeting Intersect and Minus if its input has unique keys
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdUniqueKeys.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
Labels: LGTM-will-merge-soon

#2109 [CALCITE-3920] Improve ORDER BY computation in Enumerable convention by exploiting LIMIT
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimit.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimitSort.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimitSortRule.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRules.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableSort.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
  linq4j/src/test/java/org/apache/calcite/linq4j/test/LimitSortTest.java
Labels: LGTM-will-merge-soon

#2129 [CALCITE-4206] RelDecorrelator outputs wrong plan for correlate sort …
  core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
Labels: LGTM-will-merge-soon

#2131 [CALCITE-4208] Improve metadata row count for Join
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java
  core/src/main/java/org/apache/calcite/util/NumberUtil.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
  core/src/test/resources/sql/sub-query.iq
Labels: LGTM-will-merge-soon, slow-tests-needed

#2140 [CALCITE-4229] Add Util.throwAsRuntime and Util.causeOrSelf to simplify exception re-throwing
  core/src/main/java/org/apache/calcite/materialize/CachingLatticeStatisticProvider.java
  core/src/main/java/org/apache/calcite/rel/metadata/ChainedRelMetadataProvider.java
  core/src/main/java/org/apache/calcite/rel/metadata/JaninoRelMetadataProvider.java
  core/src/main/java/org/apache/calcite/rel/metadata/MetadataFactoryImpl.java
  core/src/main/java/org/apache/calcite/rel/metadata/ReflectiveRelMetadataProvider.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperatorTableFactory.java
  core/src/main/java/org/apache/calcite/sql/pretty/SqlPrettyWriter.java
  core/src/main/java/org/apache/calcite/sql/type/SqlTypeMappingRules.java
  core/src/main/java/org/apache/calcite/sql/util/ReflectiveSqlOperatorTable.java
  core/src/main/java/org/apache/calcite/statistic/CachingSqlStatisticProvider.java
  core/src/main/java/org/apache/calcite/util/ReflectUtil.java
  core/src/main/java/org/apache/calcite/util/Util.java
  druid/src/main/java/org/apache/calcite/adapter/druid/DruidConnectionImpl.java
Labels: LGTM-will-merge-soon

#2134 [CALCITE-4217] Unlock RelCrossType#getFieldCount()
  core/src/main/java/org/apache/calcite/rel/type/RelCrossType.java
  core/src/main/java/org/apache/calcite/rel/type/RelDataTypeImpl.java
Labels: LGTM-will-merge-soon

#2144 [CALCITE-4237] Sarg with single IS NULL operand causes AssertionError
  core/src/main/java/org/apache/calcite/rex/RexSimplify.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
  plus/src/test/java/org/apache/calcite/adapter/tpcds/TpcdsTest.java
Labels: slow-tests-needed

#2128 [CALCITE-4197] Provide utility to visualize RelNode plans
  core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
  core/src/main/java/org/apache/calcite/rel/externalize/RelDotWriter.java
  core/src/main/java/org/apache/calcite/rel/externalize/RelWriterImpl.java
  core/src/main/java/org/apache/calcite/sql/SqlExplainFormat.java
  core/src/test/java/org/apache/calcite/plan/RelWriterTest.java
  core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java
  core/src/test/java/org/apache/calcite/test/HepPlannerTest.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
Labels: LGTM-will-merge-soon

#2145 [CALCITE-4239] RelMdUniqueKeys returns wrong unique keys for Aggregate with grouping sets
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnUniqueness.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdUniqueKeys.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
Labels: LGTM-will-merge-soon

#2152 [CALCITE-4258] SqlToRelConverter: SELECT 1 IS [NOT] DISTINCT FROM NULL fails with AssertionError
  core/src/main/java/org/apache/calcite/plan/RelOptPredicateList.java
  core/src/test/resources/sql/misc.iq
Labels: LGTM-will-merge-soon, slow-tests-needed

#2146 [CALCITE-4241] Some improvements to metadata query
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnUniqueness.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdDistinctRowCount.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
Labels: LGTM-will-merge-soon

#2143 [CALCITE-4224] Add an method for RelNode to output its tree digest like RelOptUtil.toString (Jiatao Tao)
  core/src/main/java/org/apache/calcite/rel/RelNode.java
  core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java
Labels: LGTM-will-merge-soon

#2160 [CALCITE-4269] Improvement on enumerable implementation for HOP and SESSION
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java
Labels: LGTM-will-merge-soon

#2130 [CALCITE-4207] Validation fails for positional aggregate with current_date in 'case' expression
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorUtil.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
  core/src/test/java/org/apache/calcite/test/catalog/Fixture.java
Labels: LGTM-will-merge-soon

#2168 [CALCITE-4275] EnumerableMergeJoin#create does not set EnumerableConvention in the trait set
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#2164 [CALCITE-4176] Key descriptor can be optional in SESSION table function
  core/src/main/java/org/apache/calcite/sql/SqlHopTableFunction.java
  core/src/main/java/org/apache/calcite/sql/SqlSessionTableFunction.java
  core/src/main/java/org/apache/calcite/sql/SqlTumbleTableFunction.java
  core/src/main/java/org/apache/calcite/sql/SqlWindowTableFunction.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Labels: LGTM-will-merge-soon

#2135 [CALCITE-4214] Make RelDataType.getSqlTypeName non-nullable
  core/src/main/java/org/apache/calcite/rel/type/RelDataType.java
  core/src/main/java/org/apache/calcite/rel/type/RelDataTypeImpl.java
Labels: LGTM-will-merge-soon

#2179 Fix grammatical errors
  site/_docs/algebra.md
  site/_docs/druid_adapter.md
  site/_docs/elasticsearch_adapter.md
Labels: LGTM-will-merge-soon

#2177 [CALCITE-4287] AggregateJoinRemoveRule and ProjectJoinRemoveRule are not fired if the last column of the join's left input is referenced
  core/src/main/java/org/apache/calcite/rel/rules/AggregateJoinRemoveRule.java
  core/src/main/java/org/apache/calcite/rel/rules/ProjectJoinRemoveRule.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon, slow-tests-needed

#2180 Fix adapter doc grammatical errors
  site/_docs/file_adapter.md
Labels: LGTM-will-merge-soon

#2171 [CALCITE-4288] Create SqlTypeUtil#deriveType(SqlCallBinding) to make type computation simpler
  core/src/main/java/org/apache/calcite/sql/SqlCallBinding.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlCaseOperator.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlCastFunction.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlDotOperator.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlLiteralChainOperator.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlMapValueConstructor.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlMultisetMemberOfOperator.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlMultisetQueryConstructor.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlMultisetValueConstructor.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlSubstringFunction.java
  core/src/main/java/org/apache/calcite/sql/type/AssignableOperandTypeChecker.java
  core/src/main/java/org/apache/calcite/sql/type/FamilyOperandTypeChecker.java
  core/src/main/java/org/apache/calcite/sql/type/InferTypes.java
  core/src/main/java/org/apache/calcite/sql/type/MultisetOperandTypeChecker.java
  core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
  core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java
Labels: LGTM-will-merge-soon

#2173 [CALCITE-4216] Make org.apache.calcite.rel.type.RelDataType#getFamily non-nullable
  core/src/main/java/org/apache/calcite/rel/type/RelDataType.java
  core/src/main/java/org/apache/calcite/sql/type/AbstractSqlType.java
  core/src/main/java/org/apache/calcite/sql/type/ObjectSqlType.java
Labels: LGTM-will-merge-soon
