Repository apache/calcite, pull requests merged in 2020-04, with the labels that each got.

#1894 [CALCITE-3888] Switch avatica-server to be test dependency for core
  core/build.gradle.kts
Labels: LGTM-will-merge-soon

#1891 Site: Fix links to javadoc
  site/_docs/adapter.md
Labels: LGTM-will-merge-soon

#1898 Add JIRA links in Git in IDEA
  .gitignore
  .idea/vcs.xml
  .ratignore
Labels: LGTM-will-merge-soon

#1873 [CALCITE-3872] Simplify expressions with unary minus
  core/src/main/java/org/apache/calcite/rex/RexAnalyzer.java
  core/src/main/java/org/apache/calcite/rex/RexSimplify.java
  core/src/test/java/org/apache/calcite/rex/RexProgramBuilderBase.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
Labels: LGTM-will-merge-soon

#1853 [CALCITE-3851] Replace the node importance map with a set for pruned nodes
  core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java
  core/src/main/java/org/apache/calcite/plan/RelOptPlanner.java
  core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java
  core/src/main/java/org/apache/calcite/plan/volcano/RuleQueue.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
  core/src/main/java/org/apache/calcite/rel/rules/AggregateCaseToFilterRule.java
  core/src/main/java/org/apache/calcite/rel/rules/AggregateValuesRule.java
  core/src/main/java/org/apache/calcite/rel/rules/CalcMergeRule.java
  core/src/main/java/org/apache/calcite/rel/rules/ExchangeRemoveConstantKeysRule.java
  core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
  core/src/main/java/org/apache/calcite/rel/rules/SortRemoveConstantKeysRule.java
  core/src/main/java/org/apache/calcite/rel/rules/ValuesReduceRule.java
  core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java
Labels: LGTM-will-merge-soon, discussion-in-jira, returned-with-feedback

#1837 [CALCITE-3835] Overloaded table functions fail with an assertion error if param types differ
  core/src/main/java/org/apache/calcite/sql/SqlUtil.java
  core/src/test/java/org/apache/calcite/test/JdbcTest.java
  core/src/test/java/org/apache/calcite/util/Smalls.java
Labels: LGTM-will-merge-soon

#1903 [CALCITE-3900] Add Config for SqlValidator
  core/src/main/java/org/apache/calcite/jdbc/CalciteConnectionImpl.java
  core/src/main/java/org/apache/calcite/prepare/CalcitePrepareImpl.java
  core/src/main/java/org/apache/calcite/prepare/CalciteSqlValidator.java
  core/src/main/java/org/apache/calcite/prepare/PlannerImpl.java
  core/src/main/java/org/apache/calcite/sql/SqlCallBinding.java
  core/src/main/java/org/apache/calcite/sql/SqlFunction.java
  core/src/main/java/org/apache/calcite/sql/SqlOperator.java
  core/src/main/java/org/apache/calcite/sql/SqlWindow.java
  core/src/main/java/org/apache/calcite/sql/advise/SqlAdvisorValidator.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlCaseOperator.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlInOperator.java
  core/src/main/java/org/apache/calcite/sql/type/ComparableOperandTypeChecker.java
  core/src/main/java/org/apache/calcite/sql/type/CompositeOperandTypeChecker.java
  core/src/main/java/org/apache/calcite/sql/type/FamilyOperandTypeChecker.java
  core/src/main/java/org/apache/calcite/sql/type/SameOperandTypeExceptLastOperandChecker.java
  core/src/main/java/org/apache/calcite/sql/type/SetopOperandTypeChecker.java
  core/src/main/java/org/apache/calcite/sql/validate/IdentifierNamespace.java
  core/src/main/java/org/apache/calcite/sql/validate/OrderByScope.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidator.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorUtil.java
  core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
  core/src/main/java/org/apache/calcite/tools/FrameworkConfig.java
  core/src/main/java/org/apache/calcite/tools/Frameworks.java
  core/src/main/java/org/apache/calcite/util/ImmutableBeans.java
  core/src/test/java/org/apache/calcite/rel/logical/ToLogicalConverterTest.java
  core/src/test/java/org/apache/calcite/sql/test/SqlAdvisorTest.java
  core/src/test/java/org/apache/calcite/sql/test/SqlTestFactory.java
  core/src/test/java/org/apache/calcite/test/SqlTestGen.java
  core/src/test/java/org/apache/calcite/test/SqlToRelTestBase.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorFeatureTest.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTestCase.java
Labels: LGTM-will-merge-soon

#1883 [CALCITE-3833] Support SemiJoin in EnumerableMergeJoin
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoinRule.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdCollation.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Labels: LGTM-will-merge-soon

#1889 [CALCITE-3576] Remove enumerable convention check in FilterIntoJoinRule
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableNestedLoopJoin.java
  core/src/main/java/org/apache/calcite/rel/rules/FilterJoinRule.java
  core/src/test/java/org/apache/calcite/test/MaterializationTest.java
  core/src/test/resources/sql/join.iq
  core/src/test/resources/sql/sub-query.iq
Labels: LGTM-will-merge-soon, slow-tests-needed

#1907 [CALCITE-3909] RelMdMinRowCount doesn't take into account UNION DISTINCT
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdMinRowCount.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
Labels: LGTM-will-merge-soon

#1900 [CALCITE-3733] MySQL JDBC rewrite should rewrite CAST as TIMESTAMP to CAST as DATETIME (Vineet Garg)
  core/src/main/java/org/apache/calcite/sql/dialect/MysqlSqlDialect.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Labels: LGTM-will-merge-soon

#1920 [CALCITE-3894] The Union operation between DATE with TIMESTAMP return…
  core/src/main/java/org/apache/calcite/sql/type/SqlTypeAssignmentRule.java
  core/src/test/java/org/apache/calcite/test/JdbcTest.java
  core/src/test/java/org/apache/calcite/test/TypeCoercionConverterTest.java
  core/src/test/java/org/apache/calcite/test/TypeCoercionTest.java
  core/src/test/resources/org/apache/calcite/test/TypeCoercionConverterTest.xml
Labels: LGTM-will-merge-soon

#1800 [CALCITE-3790] Make the url() of Sources.of(file) available
  core/src/main/java/org/apache/calcite/util/Sources.java
  core/src/test/java/org/apache/calcite/util/SourceTest.java
Labels: returned-with-feedback

#1926 [CALCITE-3447] MutableScans with the same qualified name are not equivalent.
  core/src/main/java/org/apache/calcite/rel/mutable/MutableScan.java
  core/src/test/java/org/apache/calcite/test/MutableRelTest.java
Labels: LGTM-will-merge-soon

#1869 [CALCITE-3868] Remove redundant ruleSet and ruleNames in VolcanoPlanner
  core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java
  core/src/main/java/org/apache/calcite/plan/RelOptRule.java
  core/src/main/java/org/apache/calcite/plan/hep/HepPlanner.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
  core/src/test/resources/sql/sub-query.iq
Labels: LGTM-will-merge-soon, slow-tests-needed

#1933 [CALCITE-3937] Fire rule for RelSubset only when it is derived
  core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java
  core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Labels: LGTM-will-merge-soon

#1932 [CALCITE-3944] Move dumpSets and dumpGraphviz out of VolcanoPlanner
  core/src/main/java/org/apache/calcite/plan/volcano/Dumpers.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Labels: LGTM-will-merge-soon

#1775 [CALCITE-3758] FilterTableScanRule generate wrong mapping for filter …
  core/src/main/java/org/apache/calcite/interpreter/Bindables.java
  core/src/main/java/org/apache/calcite/rel/rules/FilterTableScanRule.java
  core/src/test/java/org/apache/calcite/test/ScannableTableTest.java
Labels: LGTM-will-merge-soon

#1943 [CALCITE-3955] Remove the first operand of RexCall from SqlWindowTabl…
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
Labels: LGTM-will-merge-soon

#1942 [CALCITE-3954] Always compare types using equals
  core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
  core/src/main/java/org/apache/calcite/rel/type/RelDataTypeImpl.java
  core/src/main/java/org/apache/calcite/rex/RexLocalRef.java
  core/src/main/java/org/apache/calcite/rex/RexUtil.java
  core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java
Labels: LGTM-will-merge-soon

#1952 [CALCITE-3949] RelDistributions.of() and RelCollations.of() should canonize trait instance
  core/src/main/java/org/apache/calcite/rel/RelCollations.java
  core/src/main/java/org/apache/calcite/rel/RelDistributions.java
Labels: LGTM-will-merge-soon

#1925 [CALCITE-3938] Support LogicalCalc in RelShuttle
  core/src/main/java/org/apache/calcite/prepare/CalciteMaterializer.java
  core/src/main/java/org/apache/calcite/rel/RelShuttle.java
  core/src/main/java/org/apache/calcite/rel/RelShuttleImpl.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
Labels: LGTM-will-merge-soon
