Repository apache/calcite, pull requests merged in 2020-06, with the labels that each got.

#2000 [CALCITE-4040] An aggregate function that does not support roll up throws an exception when it is rolled up
  core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java
  core/src/test/java/org/apache/calcite/test/MaterializedViewSubstitutionVisitorTest.java
Labels: LGTM-will-merge-soon

#2007 [CALCITE-4049] Reduce the time complexity of getting shortest distances
  core/src/main/java/org/apache/calcite/runtime/ConsList.java
  core/src/main/java/org/apache/calcite/util/graph/Graphs.java
  core/src/test/java/org/apache/calcite/util/graph/DirectedGraphTest.java
Labels: LGTM-will-merge-soon

#2015 [CALCITE-4055] RelFieldTrimmer loses hints
  core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java
  core/src/main/java/org/apache/calcite/tools/RelBuilder.java
  core/src/test/java/org/apache/calcite/sql2rel/RelFieldTrimmerTest.java
Labels: LGTM-will-merge-soon

#2016 [CALCITE-3786] Add Digest interface to enable efficient hashCode(equa…
  core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcRules.java
  core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java
  core/src/main/java/org/apache/calcite/plan/Digest.java
  core/src/main/java/org/apache/calcite/plan/MaterializedViewSubstitutionVisitor.java
  core/src/main/java/org/apache/calcite/plan/RelOptNode.java
  core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
  core/src/main/java/org/apache/calcite/plan/hep/HepPlanner.java
  core/src/main/java/org/apache/calcite/plan/hep/HepRelVertex.java
  core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
  core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java
  core/src/main/java/org/apache/calcite/rel/RelNode.java
  core/src/main/java/org/apache/calcite/rel/RelWriter.java
  core/src/main/java/org/apache/calcite/rel/core/Match.java
  core/src/main/java/org/apache/calcite/rel/core/Window.java
  core/src/main/java/org/apache/calcite/rel/externalize/RelJsonWriter.java
  core/src/main/java/org/apache/calcite/rel/externalize/RelWriterImpl.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdExpressionLineage.java
  core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
  core/src/main/java/org/apache/calcite/rel/rules/JoinProjectTransposeRule.java
  core/src/main/java/org/apache/calcite/rel/rules/ProjectWindowTransposeRule.java
  core/src/main/java/org/apache/calcite/rel/rules/materialize/MaterializedViewAggregateRule.java
  core/src/main/java/org/apache/calcite/rel/rules/materialize/MaterializedViewJoinRule.java
  core/src/main/java/org/apache/calcite/rel/rules/materialize/MaterializedViewRule.java
  core/src/main/java/org/apache/calcite/rex/RexCall.java
  core/src/main/java/org/apache/calcite/rex/RexNode.java
  core/src/main/java/org/apache/calcite/rex/RexOver.java
  core/src/main/java/org/apache/calcite/rex/RexSubQuery.java
  core/src/main/java/org/apache/calcite/sql/SqlKind.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
  core/src/test/java/org/apache/calcite/materialize/LatticeSuggesterTest.java
  core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java
  core/src/test/java/org/apache/calcite/plan/volcano/TraitPropagationTest.java
  core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java
  core/src/test/java/org/apache/calcite/rel/rules/DateRangeRulesTest.java
  core/src/test/java/org/apache/calcite/rex/RexCallNormalizationTest.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTestBase.java
  core/src/test/java/org/apache/calcite/rex/RexSqlStandardConvertletTableTest.java
  core/src/test/java/org/apache/calcite/test/HepPlannerTest.java
  core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
  core/src/test/java/org/apache/calcite/test/LatticeTest.java
  core/src/test/java/org/apache/calcite/test/MaterializedViewRelOptRulesTest.java
  core/src/test/java/org/apache/calcite/test/MaterializedViewSubstitutionVisitorTest.java
  core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/java/org/apache/calcite/test/RexTransformerTest.java
  core/src/test/java/org/apache/calcite/test/SqlHintsConverterTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableCorrelateTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
  core/src/test/resources/org/apache/calcite/test/TopDownOptTest.xml
  core/src/test/resources/sql/blank.iq
  core/src/test/resources/sql/sub-query.iq
  druid/src/main/java/org/apache/calcite/adapter/druid/DruidRules.java
  piglet/src/main/java/org/apache/calcite/piglet/PigToSqlAggregateRule.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#1987 [CALCITE-4020] Support Calc operator in RelFieldTrimmer
  core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java
  core/src/test/java/org/apache/calcite/sql2rel/RelFieldTrimmerTest.java
Labels: LGTM-will-merge-soon

#2020 [CALCITE-4060] Supports implicit type coercion for NOT IN.
  core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercionImpl.java
  core/src/test/java/org/apache/calcite/test/TypeCoercionConverterTest.java
  core/src/test/resources/org/apache/calcite/test/TypeCoercionConverterTest.xml
Labels: LGTM-will-merge-soon

#1937 [CALCITE-3951] Support different string comparison based on SqlCollation
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/PhysTypeImpl.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
  core/src/main/java/org/apache/calcite/jdbc/JavaCollation.java
  core/src/main/java/org/apache/calcite/rex/RexBuilder.java
  core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
  core/src/main/java/org/apache/calcite/runtime/Utilities.java
  core/src/main/java/org/apache/calcite/sql/SqlCollation.java
  core/src/main/java/org/apache/calcite/sql/SqlUtil.java
  core/src/main/java/org/apache/calcite/sql/parser/SqlParserUtil.java
  core/src/main/java/org/apache/calcite/sql/type/SqlTypeFactoryImpl.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/main/java/org/apache/calcite/util/NlsString.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableStringComparisonTest.java
  linq4j/src/main/java/org/apache/calcite/linq4j/function/Functions.java
Labels: slow-tests-needed

#2036 [CALCITE-3786] Add Digest interface to enable efficient hashCode(equa…
  core/src/main/java/org/apache/calcite/plan/Digest.java
  core/src/main/java/org/apache/calcite/plan/hep/HepRelVertex.java
  core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java
  core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableCorrelateTest.java
Labels: LGTM-will-merge-soon

#2004 [CALCITE-4019] Visit SqlInsert with SqlShuttle cause NullPointerExcep…
  core/src/main/java/org/apache/calcite/sql/SqlInsert.java
  core/src/main/java/org/apache/calcite/sql/parser/SqlParserPos.java
  core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
Labels: LGTM-will-merge-soon

#2039 Digest on RelNode and RexCall
  core/src/main/java/org/apache/calcite/plan/Digest.java
  core/src/main/java/org/apache/calcite/plan/RelDigest.java
  core/src/main/java/org/apache/calcite/plan/RelOptNode.java
  core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
  core/src/main/java/org/apache/calcite/plan/hep/HepPlanner.java
  core/src/main/java/org/apache/calcite/plan/hep/HepRelVertex.java
  core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
  core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java
  core/src/main/java/org/apache/calcite/rel/RelNode.java
  core/src/main/java/org/apache/calcite/rel/SingleRel.java
  core/src/main/java/org/apache/calcite/rel/core/Window.java
  core/src/main/java/org/apache/calcite/rel/metadata/JaninoRelMetadataProvider.java
  core/src/main/java/org/apache/calcite/rel/rules/MultiJoin.java
  core/src/main/java/org/apache/calcite/rex/RexCall.java
  core/src/main/java/org/apache/calcite/rex/RexDynamicParam.java
  core/src/main/java/org/apache/calcite/rex/RexLiteral.java
  core/src/main/java/org/apache/calcite/rex/RexOver.java
  core/src/main/java/org/apache/calcite/rex/RexSubQuery.java
  core/src/test/java/org/apache/calcite/test/HepPlannerTest.java
Labels: slow-tests-needed

#2044 [CALCITE-3786] Make digestEquals and digestHash available to be overridden
  core/src/main/java/org/apache/calcite/plan/RelOptNode.java
  core/src/main/java/org/apache/calcite/plan/hep/HepRelVertex.java
  core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java
  core/src/main/java/org/apache/calcite/rel/RelNode.java
  core/src/main/java/org/apache/calcite/rel/core/Filter.java
  core/src/main/java/org/apache/calcite/rel/core/Join.java
  core/src/main/java/org/apache/calcite/rel/core/Project.java
  core/src/main/java/org/apache/calcite/rel/logical/LogicalFilter.java
  core/src/main/java/org/apache/calcite/rel/logical/LogicalJoin.java
  core/src/main/java/org/apache/calcite/rel/logical/LogicalProject.java
  core/src/main/java/org/apache/calcite/rel/type/RelDataType.java
Labels: slow-tests-needed

#2022 [CALCITE-4062] Support deserialize UDF array type from json string
  core/src/main/java/org/apache/calcite/rel/externalize/RelJson.java
  core/src/test/java/org/apache/calcite/plan/RelWriterTest.java
  core/src/test/java/org/apache/calcite/test/MockSqlOperatorTable.java
Labels: LGTM-will-merge-soon

#1964 Site: Add Tencent and TBDS logo in powered-by image
  site/_docs/powered_by.md
  site/img/powered-by.png
Labels: LGTM-will-merge-soon

#1955 [CALCITE-3941] Add the default strict mode to the path in the Json functions
  core/src/main/java/org/apache/calcite/runtime/JsonFunctions.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/java/org/apache/calcite/test/SqlJsonFunctionsTest.java
Labels: LGTM-will-merge-soon

#2021 [CALCITE-3929] When deserialize UDAF aggregate call from json string,…
  core/src/main/java/org/apache/calcite/rel/externalize/RelJson.java
  core/src/test/java/org/apache/calcite/plan/RelWriterTest.java
  core/src/test/java/org/apache/calcite/test/MockSqlOperatorTable.java
Labels: LGTM-will-merge-soon
