Repository apache/calcite, pull requests merged in 2020-03, with the labels that each got.

#1841 Following CALCITE-3769: Add BindableTableScanRule into the default ru…
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScan.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScanRule.java
  core/src/main/java/org/apache/calcite/interpreter/Bindables.java
  core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
  core/src/test/java/org/apache/calcite/test/StreamTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionHierarchyTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionTest.java
  example/csv/src/main/java/org/apache/calcite/adapter/csv/CsvFilterableTable.java
  example/csv/src/main/java/org/apache/calcite/adapter/csv/CsvScannableTable.java
  example/csv/src/main/java/org/apache/calcite/adapter/csv/CsvStreamScannableTable.java
  example/csv/src/main/java/org/apache/calcite/adapter/csv/CsvTable.java
  example/csv/src/main/java/org/apache/calcite/adapter/csv/CsvTranslatableTable.java
  example/csv/src/main/java/org/apache/calcite/adapter/csv/JsonEnumerator.java
  example/csv/src/main/java/org/apache/calcite/adapter/csv/JsonScannableTable.java
  example/csv/src/main/java/org/apache/calcite/adapter/csv/JsonTable.java
  example/csv/src/test/java/org/apache/calcite/test/CsvTest.java
Labels: slow-tests-needed

#1843 [CALCITE-3837] AntiJoin with empty right input can always be transformed as its left input
  core/src/main/java/org/apache/calcite/rel/rules/PruneEmptyRules.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon

#1826 [CALCITE-3820] EnumerableDefaults#orderBy should be lazily computed + support enumerator re-initialization
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableJoinTest.java
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Labels: LGTM-will-merge-soon

#1833 [CALCITE-3828] MergeJoin throws NPE in case of null keys
  core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Labels: LGTM-will-merge-soon

#1818 [CALCITE-3809] RexSimplify simplifies nondeterministic function incorrectly
  core/src/main/java/org/apache/calcite/rex/RexAnalyzer.java
  core/src/main/java/org/apache/calcite/rex/RexInterpreter.java
  core/src/main/java/org/apache/calcite/rex/RexSimplify.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
Labels: LGTM-will-merge-soon

#1829 [CALCITE-3819] Prune parent RelNode when merging child RelSet with parent RelSet
  core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#1842 [CALCITE-3838] Support Calc in RelMdSize,RelMdSelectivity,RelMdMaxRowCount,RelMdMinRowCount,RelMdTableReferences
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdMaxRowCount.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdMinRowCount.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdSelectivity.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdSize.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdTableReferences.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#1848 [CALCITE-3845] CASE WHEN expression with nullability CAST is considered as reduced wrongly in ReduceExpressionsRule
  core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon

#1857 [CALCITE-3853] Minor improvements in SortJoinCopyRule
  core/src/main/java/org/apache/calcite/rel/rules/SortJoinCopyRule.java
Labels: LGTM-will-merge-soon

#1856 [CALCITE-3856] Remove code to be removed before 1.23
  core/src/main/java/org/apache/calcite/rel/core/RelFactories.java
  core/src/main/java/org/apache/calcite/rel/logical/LogicalJoin.java
  core/src/main/java/org/apache/calcite/rel/logical/LogicalProject.java
  core/src/main/java/org/apache/calcite/rel/logical/LogicalTableScan.java
  core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
  core/src/main/java/org/apache/calcite/rel/stream/StreamRules.java
  core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
  core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
  core/src/test/java/org/apache/calcite/test/RelOptTestBase.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTestCase.java
  pig/src/main/java/org/apache/calcite/adapter/pig/PigRelFactories.java
Labels: slow-tests-needed

#1768 [CALCITE-3704] Implement STRCMP function
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/resources/sql/functions.iq
  site/_docs/reference.md
Labels: LGTM-will-merge-soon

#1849 [CALCITE-3815] Add missing SQL standard aggregate functions: EVERY, SO…
  core/src/main/codegen/templates/Parser.jj
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/sql/SqlKind.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlMinMaxAggFunction.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
  core/src/test/java/org/apache/calcite/sql/test/SqlAdvisorTest.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
  core/src/test/resources/sql/agg.iq
  site/_docs/reference.md
Labels: LGTM-will-merge-soon

#1725 [CALCITE-3694] Implement SINH function
  babel/src/test/resources/sql/redshift.iq
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/resources/sql/functions.iq
  site/_docs/reference.md
Labels: LGTM-will-merge-soon

#1696 [CALCITE-3634] Add IntersectOnCalcsToIntersectUnifyRule for materialized view recognition
  core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java
  core/src/main/java/org/apache/calcite/rel/mutable/MutableSetOp.java
  core/src/test/java/org/apache/calcite/test/MaterializationTest.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#1854 [CALCITE-3852] RexSimplify doesn't simplify NOT EQUAL predicates
  core/src/main/java/org/apache/calcite/rex/RexSimplify.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
  core/src/test/java/org/apache/calcite/test/MaterializationTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon, slow-tests-needed

#1788 [CALCITE-3285] EnumerableMergeJoin should support non-equi join conditions
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoinRule.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableJoinTest.java
  linq4j/build.gradle.kts
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Labels: LGTM-will-merge-soon

#1864 [CALCITE-3829] MergeJoinEnumerator should not use inputs enumerators until it is really required
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Labels: LGTM-will-merge-soon

#1874 Update Gradle: 6.1.1 -> 6.3
  .github/workflows/main.yml
  .travis.yml
  buildSrc/subprojects/javacc/src/main/kotlin/org/apache/calcite/buildtools/javacc/JavaCCTask.kt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: slow-tests-needed

#1870 [CALCITE-3846] EnumerableMergeJoin: wrong comparison of composite key with null values
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableJoinTest.java
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Labels: LGTM-will-merge-soon

#1862 [CALCITE-3864] Supports CONCAT for variable arguments
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
  core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/resources/sql/functions.iq
  site/_docs/reference.md
Labels: LGTM-will-merge-soon

#1887 [CALCITE-3886] Execute substitution rule according to the order they get matched
  core/src/main/java/org/apache/calcite/plan/SubstitutionRule.java
  core/src/main/java/org/apache/calcite/plan/volcano/RuleQueue.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
  core/src/main/java/org/apache/calcite/rel/rules/AggregateRemoveRule.java
  core/src/main/java/org/apache/calcite/rel/rules/PruneEmptyRules.java
Labels: slow-tests-needed

#1888 Following [CALCITE-3819] Prune parent RelNode when merging child RelSet with parent RelSet
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
Labels: slow-tests-needed
