Repository apache/calcite, pull requests merged in 2020-05, with the labels that each got.

#1956 [CALCITE-3966] Trigger rules for existing RelSubset when it becomes delivered
  core/src/main/java/org/apache/calcite/plan/Convention.java
  core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java
  core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Labels: slow-tests-needed

#1960 [CALCITE-3971] Support Calc in RelMdColumnOrigins
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#1892 [CALCITE-3887] Filter and Join conditions may not need to retain null…
  core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
  core/src/main/java/org/apache/calcite/rex/RexSimplify.java
  core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon

#1954 [CALCITE-3965] Avoid DiffRepository lock contention
  core/src/test/java/org/apache/calcite/test/DiffRepository.java
Labels: slow-tests-needed

#1918 [CALCITE-3926] CannotPlanException when an empty LogicalValues requires a certain collation
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableValues.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableValuesRule.java
  core/src/main/java/org/apache/calcite/rel/logical/LogicalValues.java
  core/src/main/java/org/apache/calcite/rel/rules/PruneEmptyRules.java
  core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon, slow-tests-needed

#1867 [CALCITE-3866] "numeric field overflow" when running the generated SQL in PostgreSQL
  core/src/main/java/org/apache/calcite/rel/type/RelDataTypeSystemImpl.java
  core/src/main/java/org/apache/calcite/sql/SqlSplittableAggFunction.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/resources/sql/agg.iq
Labels: LGTM-will-merge-soon

#1969 [CALCITE-3979] Simplification might have removed CAST expressi…
  core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon, slow-tests-needed

#1979 Following [CALCITE-3997] Remove TransformationRule from CalcMergeRule temporarily
  core/src/main/java/org/apache/calcite/rel/rules/CalcMergeRule.java
Labels: slow-tests-needed

#1988 [CALCITE-4019] Visit SqlInsert with SqlShuttle cause NullPointerException
  core/src/main/java/org/apache/calcite/sql/SqlInsert.java
  core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
Labels: LGTM-will-merge-soon
