Repository apache/calcite, pull requests merged in 2020-11, with the labels that each got.

#2239 Following [CALCITE-4332] correct the code style and add some description
  core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
  core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java
Labels: LGTM-will-merge-soon

#2231 [CALCITE-4350] The reverse operation of collation direction is overly relaxed
  core/src/main/java/org/apache/calcite/rel/RelFieldCollation.java
  core/src/test/java/org/apache/calcite/rel/RelCollationTest.java
Labels: LGTM-will-merge-soon

#2243 Fix grammatical errors in TopDownRuleDriver/TopDownRuleQueue/RuleDriver/VolcanoPlanner
  core/src/main/java/org/apache/calcite/plan/volcano/RuleDriver.java
  core/src/main/java/org/apache/calcite/plan/volcano/TopDownRuleDriver.java
  core/src/main/java/org/apache/calcite/plan/volcano/TopDownRuleQueue.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Labels: LGTM-will-merge-soon

#2241 [CALCITE-4374] Support materialized view recognition when query disti…
  core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java
  core/src/test/java/org/apache/calcite/test/MaterializedViewSubstitutionVisitorTest.java
Labels: LGTM-will-merge-soon

#2254 [CALCITE-4390] Fix SqlMatchRecognize operand list
  core/src/main/java/org/apache/calcite/sql/SqlMatchRecognize.java
  core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#2257 Following 4364, fix the plann diff of TpcdsTest
  plus/src/test/java/org/apache/calcite/adapter/tpcds/TpcdsTest.java
Labels: slow-tests-needed

#2265 Following [CALCITE-4364], fix the plan diff of TpcdsTest
  plus/src/test/java/org/apache/calcite/adapter/tpcds/TpcdsTest.java
Labels: slow-tests-needed

#2256 [CALCITE-4392] The operation of checking types equal ignoring null can be more efficient
  core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java
  core/src/test/java/org/apache/calcite/sql/type/SqlTypeUtilTest.java
Labels: LGTM-will-merge-soon

#2222 [CALCITE-4277] When rel has been removed from its subset, skip the origin rule match (Jiatao Tao)
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
Labels: LGTM-will-merge-soon

#2269 [CALCITE-4406] SqlTableRef OPERATOR should create a SqlTableRef as th…
  core/src/main/java/org/apache/calcite/sql/SqlHint.java
  core/src/main/java/org/apache/calcite/sql/SqlTableRef.java
  core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
Labels: LGTM-will-merge-soon

#2189 [CALCITE-4251] Get the origin column, even if it is derived (xzh)
  core/src/main/java/org/apache/calcite/rel/metadata/RelMetadataQuery.java
  core/src/main/java/org/apache/calcite/rel/rules/LoptMultiJoin.java
  core/src/main/java/org/apache/calcite/rel/rules/LoptOptimizeJoinRule.java
  core/src/main/java/org/apache/calcite/rel/rules/LoptSemiJoinOptimizer.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
  site/_docs/history.md
Labels: LGTM-will-merge-soon

#2266 [CALCITE-4402] SqlCall#equalsDeep does not take into account the function quantifier
  core/src/main/java/org/apache/calcite/sql/SqlCall.java
  core/src/test/java/org/apache/calcite/sql/test/SqlEqualsDeepTest.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#2255 [CALCITE-4393] ExceptionInInitializerError due to NPE in SqlCallBinding caused by circular dependency
  core/src/main/java/org/apache/calcite/sql/SqlCallBinding.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#2272 [CALCITE-4409] Improve exception when RelBuilder tries to create a field on a non-struct expression
  core/src/main/java/org/apache/calcite/rel/type/RelDataTypeImpl.java
  core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
Labels: LGTM-will-merge-soon

#2275 [CALCITE-4414] RelMdSelectivity#getSelectivity for Calc can propagate a predicate with wrong references
  core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdSelectivity.java
  core/src/test/java/org/apache/calcite/test/RelMdSelectivityTest.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#2211 [CALCITE-4317] RelFieldTrimmer after trimming all the fields in an ag…
  core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/java/org/apache/calcite/test/SqlToRelTestBase.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon, slow-tests-needed

#2279 [CALCITE-4415] SqlStdOperatorTable.NOT_LIKE has a wrong implementor
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlLikeOperator.java
  core/src/main/java/org/apache/calcite/tools/RelBuilder.java
  core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
  elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/PredicateAnalyzer.java
Labels: LGTM-will-merge-soon, slow-tests-needed
