Repository apache/calcite, pull requests merged in 2020-02, with the labels that each got.

#1786 [CALCITE-3773] Wrong parameter in EnumerableMergeJoin::create method
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java
Labels: LGTM-will-merge-soon

#1803 [CALCITE-3793] AssertionError throws for planner digest cache key whe…
  core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java
  core/src/main/java/org/apache/calcite/plan/hep/HepPlanner.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Labels: tests-missing

#1810 [CALCITE-3799] Following CALCITE-3769, fix the slow tests
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScanRule.java
  core/src/main/java/org/apache/calcite/plan/RelOptMaterialization.java
  core/src/test/java/org/apache/calcite/test/LatticeTest.java
Labels: slow-tests-needed

#1801 [CALCITE-3791] HepPlanner does not clear metadata cache for the ancestors of discarded node when a transformation happens
  core/src/main/java/org/apache/calcite/plan/hep/HepPlanner.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMetadataQueryBase.java
Labels: LGTM-will-merge-soon

#1812 [CALCITE-3801] Deprecate SqlToRelConverter.Config#isConvertTableAccess
  core/src/main/java/org/apache/calcite/prepare/CalcitePrepareImpl.java
  core/src/main/java/org/apache/calcite/prepare/PlannerImpl.java
  core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
  core/src/test/java/org/apache/calcite/rel/logical/ToLogicalConverterTest.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#1817 [CALCITE-3807] checkForSatisfiedConverters() is unnecessary
  core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java
  core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Labels: LGTM-will-merge-soon

#1825 [CALCITE-3817] VolcanoPlanner does not remove the entry in ruleNames when removing a rule
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Labels: LGTM-will-merge-soon

#1838 [CALCITE-3826] UPDATE assigns wrong type to bind variables
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
Labels: LGTM-will-merge-soon
