Repository apache/calcite, pull requests merged in 2020-07, with the labels that each got.

#2052 [CALCITE-4077] Exception when joined with built-in table functions
  core/src/main/java/org/apache/calcite/sql/SqlHopTableFunction.java
  core/src/main/java/org/apache/calcite/sql/SqlTumbleTableFunction.java
  core/src/main/java/org/apache/calcite/sql/SqlWindowTableFunction.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
  core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
Labels: LGTM-will-merge-soon

#2037 [CALCITE-3834] Support AntiJoin in EnumerableMergeJoin
  core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
  linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Labels: slow-tests-needed

#2061 [CALCITE-4115] Improve the prompt of using SQL keywords for sql parser
  core/src/main/codegen/templates/Parser.jj
  core/src/main/java/org/apache/calcite/sql/parser/SqlParser.java
  core/src/main/java/org/apache/calcite/sql/parser/SqlParserUtil.java
  core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
  core/src/test/java/org/apache/calcite/sql/parser/parserextensiontesting/ExtensionSqlParserTest.java
  core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Labels: LGTM-will-merge-soon

#2046 [CALCITE-4092] NPE using WITH clause without a corresponding SELECT FROM (James Kim)
  core/src/main/java/org/apache/calcite/sql/validate/WithScope.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Labels: LGTM-will-merge-soon

#2058 [CALCITE-4105] Replace Pair with Flat2List in RelDigestWriter
  core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java
  core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java
  core/src/main/java/org/apache/calcite/rel/core/Filter.java
  core/src/main/java/org/apache/calcite/rel/core/Join.java
  core/src/main/java/org/apache/calcite/rel/core/Project.java
  core/src/main/java/org/apache/calcite/rex/RexCall.java
Labels: slow-tests-needed

#2060 [CALCITE-4116] Remove unused code for tracking RexNode's nullable state in codegen
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableAggregateBase.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/NestedBlockBuilder.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/NestedBlockBuilderImpl.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/StrictAggImplementor.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/impl/WinAggResultContextImpl.java
  core/src/main/java/org/apache/calcite/interpreter/AggregateNode.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#2059 [CALCITE-4112] Refine the usage of CalciteConnectionConfig in DecorrelateProgram (Jiatao Tao)
  core/src/main/java/org/apache/calcite/config/CalciteConnectionConfig.java
  core/src/main/java/org/apache/calcite/jdbc/ContextSqlValidator.java
  core/src/main/java/org/apache/calcite/prepare/PlannerImpl.java
  core/src/main/java/org/apache/calcite/tools/Programs.java
  core/src/test/java/org/apache/calcite/test/AbstractMaterializedViewTest.java
  core/src/test/java/org/apache/calcite/test/CalciteAssert.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/java/org/apache/calcite/tools/FrameworksTest.java
  plus/src/test/java/org/apache/calcite/materialize/TpcdsLatticeSuggesterTest.java
Labels: LGTM-will-merge-soon

#2069 [CALCITE-4124] Stop invalidating metadata cache in VolcanoRuleCall
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
Labels: slow-tests-needed

#1981 [CALCITE-4000] Support OFFSET parameter in TUMBLE/HOP table functions…
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/sql/SqlHopTableFunction.java
  core/src/main/java/org/apache/calcite/sql/SqlTumbleTableFunction.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
  core/src/test/resources/sql/stream.iq
  site/_docs/reference.md
Labels: LGTM-will-merge-soon

#2065 [CALCITE-4073] Add a new component RexNormalize for more effect rex n…
  core/src/main/java/org/apache/calcite/rex/RexCall.java
  core/src/main/java/org/apache/calcite/rex/RexNode.java
  core/src/main/java/org/apache/calcite/rex/RexNormalize.java
  core/src/main/java/org/apache/calcite/sql/SqlKind.java
  core/src/main/java/org/apache/calcite/sql/SqlOperator.java
  core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java
  core/src/test/java/org/apache/calcite/rex/RexCallNormalizationTest.java
  core/src/test/java/org/apache/calcite/rex/RexNormalizeTest.java
  core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
  core/src/test/java/org/apache/calcite/test/LatticeTest.java
  core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableCorrelateTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
  core/src/test/resources/org/apache/calcite/test/TopDownOptTest.xml
  core/src/test/resources/sql/blank.iq
  core/src/test/resources/sql/sub-query.iq
Labels: LGTM-will-merge-soon, slow-tests-needed

#2071 [CALCITE-4127] Remove final from AbstractRelNode#getRelTypeName
  core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java
Labels: LGTM-will-merge-soon

#2014 [CALCITE-4022] Support unparse special syntax when operator is INSERT
  core/src/main/java/org/apache/calcite/sql/SqlSyntax.java
  core/src/main/java/org/apache/calcite/sql/SqlUtil.java
  core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
Labels: LGTM-will-merge-soon

#1057 [CALCITE-2854] Codegen compile error when implementing unary minus function with data type BigDecimal
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/java/org/apache/calcite/test/ReflectiveSchemaTest.java
Labels: LGTM-will-merge-soon

#2083 [CALCITE-4139] Prevent NPE in ListTransientTable
  core/src/main/java/org/apache/calcite/schema/impl/ListTransientTable.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionTest.java
Labels: LGTM-will-merge-soon

#2053 [CALCITE-4102] Some improvements to aggregate related operations
  core/src/main/java/org/apache/calcite/rel/core/Aggregate.java
  core/src/main/java/org/apache/calcite/sql/validate/AggregatingSelectScope.java
  core/src/main/java/org/apache/calcite/util/ImmutableBitSet.java
  core/src/main/java/org/apache/calcite/util/Util.java
  core/src/test/java/org/apache/calcite/util/ImmutableBitSetTest.java
Labels: LGTM-will-merge-soon
