Repository apache/calcite, pull requests merged in 2020-01, with the labels that each got.

#1718 [CALCITE-3666] Refine RelMdColumnUniqueness and RelMdUniqueKeys for Calc
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnUniqueness.java
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdUniqueKeys.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#1711 [CALCITE-3651] NPE when convert relational algebra that correlates TableFunctionScan
  core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Labels: LGTM-will-merge-soon

#1726 [CALCITE-3711] Correlate should override estimateRowCount
  core/src/main/java/org/apache/calcite/rel/core/Correlate.java
Labels: LGTM-will-merge-soon

#1713 [CALCITE-3658] TableModify of Update contains correlated variable by …
  core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
Labels: LGTM-will-merge-soon

#1654 [CALCITE-3587] RexBuilder may lose decimal fraction for creating literal with DECIMAL type
  core/src/main/java/org/apache/calcite/rex/RexBuilder.java
  core/src/test/java/org/apache/calcite/rex/RexBuilderTest.java
Labels: LGTM-will-merge-soon

#1591 [CALCITE-3510] Implement Redis adapter
  bom/build.gradle.kts
  build.gradle.kts
  core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
  gradle.properties
  redis/build.gradle.kts
  redis/gradle.properties
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisConfig.java
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisDataFormat.java
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisDataProcess.java
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisDataType.java
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisEnumerator.java
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisJedisManager.java
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisSchema.java
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisSchemaFactory.java
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisTable.java
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisTableFactory.java
  redis/src/main/java/org/apache/calcite/adapter/redis/RedisTableFieldInfo.java
  redis/src/main/java/org/apache/calcite/adapter/redis/package-info.java
  redis/src/test/java/org/apache/calcite/adapter/redis/RedisAdapterCaseBase.java
  redis/src/test/java/org/apache/calcite/adapter/redis/RedisCaseBase.java
  redis/src/test/java/org/apache/calcite/adapter/redis/RedisDataCaseBase.java
  redis/src/test/java/org/apache/calcite/adapter/redis/RedisMiniServer.java
  redis/src/test/resources/redis-mix-model.json
  redis/src/test/resources/start.sh
  redis/src/test/resources/stop.sh
  settings.gradle.kts
  site/_docs/adapter.md
  site/_docs/redis_adapter.md
Labels: LGTM-will-merge-soon

#1730 [CALCITE-3712] Optimize lossless casts in RexSimplify: CAST(CAST(intExpr as BIGINT) as INT) => intExpr
  core/build.gradle.kts
  core/src/main/java/org/apache/calcite/rex/RexSimplify.java
  core/src/main/java/org/apache/calcite/rex/RexUtil.java
  core/src/test/java/org/apache/calcite/rex/RexLosslessCastTest.java
  core/src/test/java/org/apache/calcite/rex/RexProgramBuilderBase.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTestBase.java
  core/src/test/java/org/apache/calcite/test/fuzzer/RexFuzzer.java
  core/src/test/java/org/apache/calcite/test/fuzzer/RexProgramFuzzyTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon

#1714 [Calcite 3663] Support for TRIM function in BigQuery dialect
  core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Labels: LGTM-will-merge-soon

#1721 [CALCITE-3677] Add assertion to EnumerableTableScan constructor to validate if the table is suitable for enumerable scan
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRelImplementor.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScan.java
  core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScanRule.java
  core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
  core/src/main/java/org/apache/calcite/prepare/RelOptTableImpl.java
  core/src/test/java/org/apache/calcite/plan/volcano/TraitPropagationTest.java
  core/src/test/java/org/apache/calcite/sql/validate/LexEscapeTest.java
  core/src/test/java/org/apache/calcite/test/ScannableTableTest.java
Labels: LGTM-will-merge-soon

#1703 [CALCITE-2450] Normalize RexCall predicates when computing digest
  core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
  core/src/main/java/org/apache/calcite/rel/RelWriter.java
  core/src/main/java/org/apache/calcite/rel/externalize/RelJsonWriter.java
  core/src/main/java/org/apache/calcite/rel/externalize/RelWriterImpl.java
  core/src/main/java/org/apache/calcite/rex/RexCall.java
  core/src/main/java/org/apache/calcite/rex/RexNode.java
  core/src/main/java/org/apache/calcite/sql/SqlKind.java
  core/src/test/java/org/apache/calcite/materialize/LatticeSuggesterTest.java
  core/src/test/java/org/apache/calcite/rel/rules/DateRangeRulesTest.java
  core/src/test/java/org/apache/calcite/rex/RexCallNormalizationTest.java
  core/src/test/java/org/apache/calcite/rex/RexProgramBuilderBase.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTestBase.java
  core/src/test/java/org/apache/calcite/test/MaterializationTest.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
  core/src/test/java/org/apache/calcite/test/RexTransformerTest.java
  core/src/test/java/org/apache/calcite/tools/FrameworksTest.java
  core/src/test/java/org/apache/calcite/tools/PlannerTest.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#1743 Use concurrent test execution by default
  build.gradle.kts
  cassandra/build.gradle.kts
  cassandra/src/test/java/org/apache/calcite/test/CassandraAdapterTest.java
  core/build.gradle.kts
  core/src/main/java/org/apache/calcite/runtime/Hook.java
  core/src/test/java/org/apache/calcite/jdbc/CalciteRemoteDriverTest.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionHierarchyTest.java
  redis/src/test/java/org/apache/calcite/adapter/redis/RedisCaseBase.java
Labels: LGTM-will-merge-soon

#1748 Use ArrayList for RuleQueue#list
  core/src/main/java/org/apache/calcite/plan/volcano/RuleQueue.java
Labels: LGTM-will-merge-soon, slow-tests-needed

#1749 Refine rules to avoid producing matches that are known to be no-op
  core/src/main/java/org/apache/calcite/rel/rules/AbstractMaterializedViewRule.java
  core/src/main/java/org/apache/calcite/rel/rules/UnionMergeRule.java
  core/src/main/java/org/apache/calcite/rel/rules/UnionPullUpConstantsRule.java
  core/src/main/java/org/apache/calcite/rel/rules/UnionToDistinctRule.java
Labels: slow-tests-needed

#1724 [CALCITE-3675] SQL to Rel conversion is broken for coalesce on nullable field
  core/src/main/java/org/apache/calcite/rex/RexCallBinding.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlCaseOperator.java
  core/src/test/java/org/apache/calcite/test/JdbcTest.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
Labels: LGTM-will-merge-soon

#1772 [CALCITE-3744] Duplicate rule matches when RelSet gets merged
  core/src/main/java/org/apache/calcite/plan/volcano/RuleQueue.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleMatch.java
Labels: slow-tests-needed

#1709 [CALCITE-3653] Support TableModify in ToLogicalConverter
  core/src/main/java/org/apache/calcite/rel/logical/ToLogicalConverter.java
  core/src/test/java/org/apache/calcite/rel/logical/ToLogicalConverterTest.java
Labels: LGTM-will-merge-soon

#1773 [CALCITE-3756] RelSubset should not match operand(RelNode.class)
  core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
  core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
Labels: slow-tests-needed
