Repository apache/calcite, pull requests merged in 2020-10, with the labels that each got.

#2184 [CALCITE-4295] Composite of two checkers with SqlOperandCountRange throws IllegalArgumentException
  core/src/main/java/org/apache/calcite/sql/type/CompositeOperandTypeChecker.java
  core/src/test/java/org/apache/calcite/test/MockSqlOperatorTable.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
Labels: LGTM-will-merge-soon, slow-tests-needed

#2195 Use jackson-bom to specify Jackson versions
  bom/build.gradle.kts
Labels: LGTM-will-merge-soon

#2198 Refactor ResultSetEnumerable to avoid try-catch in nested lambdas
  core/src/main/java/org/apache/calcite/runtime/ResultSetEnumerable.java
Labels: LGTM-will-merge-soon

#2197 [CALCITE-4316] Avoid NPE when nulls are used in divide call
  core/src/main/java/org/apache/calcite/sql/SqlBinaryOperator.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Labels: LGTM-will-merge-soon

#2194 [CALCITE-4315] NPE in RelMdUtil#checkInputForCollationAndLimit
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java
  core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
Labels: slow-tests-needed

#2156 [CALCITE-4260] Support plan explain with dot format
  core/src/main/codegen/default_config.fmpp
  core/src/main/codegen/templates/Parser.jj
  core/src/main/java/org/apache/calcite/sql/SqlExplain.java
  core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
  core/src/test/java/org/apache/calcite/test/JdbcTest.java
  example/csv/src/test/java/org/apache/calcite/test/CsvTest.java
  file/src/test/java/org/apache/calcite/adapter/file/FileAdapterTest.java
  site/_docs/reference.md
Labels: LGTM-will-merge-soon

#2226 Enable more tests in TpchTest
  core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java
  plus/src/test/java/org/apache/calcite/adapter/tpch/TpchTest.java
Labels: LGTM-will-merge-soon

#2224 [CALCITE-4332] Improve error when planning rule produces a relational…
  core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
  core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
  core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java
  core/src/test/java/org/apache/calcite/plan/volcano/PlannerTests.java
  core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java
Labels: LGTM-will-merge-soon
