Repository apache/calcite, pull requests merged in 2025-05, with the labels that each got.

#4326 [CALCITE-6977] Unparse DELETE SQL throws unsupported exception
  core/src/main/java/org/apache/calcite/sql/SqlDelete.java
  testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
Labels: LGTM-will-merge-soon

#4289 [CALCITE-6939] Add support for Lateral Column Alias
  core/src/main/java/org/apache/calcite/runtime/CalciteResource.java
  core/src/main/java/org/apache/calcite/sql/advise/SqlAdvisorValidator.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlAbstractConformance.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlConformance.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlConformanceEnum.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlDelegatingConformance.java
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
  core/src/main/resources/org/apache/calcite/runtime/CalciteResource.properties
  core/src/test/java/org/apache/calcite/test/CoreQuidemTest.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
  core/src/test/resources/sql/misc.iq
  testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Labels: LGTM-will-merge-soon

#4352 [CALCITE-6981] Runtime conversion of DECIMAL ARRAY to INT ARRAY fails…
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java
  core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  core/src/test/resources/sql/cast.iq
Labels: LGTM-will-merge-soon

#4351 [CALCITE-6995] Support FULL JOIN in StarRocks/Doris Dialect
  core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
  core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java
  core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
  testkit/src/main/java/org/apache/calcite/test/CalciteAssert.java
Labels: LGTM-will-merge-soon

#4350 [CALCITE-5387] Type-mismatch on nullability in JoinPushTransitivePredicatesRule RelRule
  core/src/main/java/org/apache/calcite/rel/metadata/RelMdPredicates.java
  core/src/main/java/org/apache/calcite/rex/RexPermuteInputsShuttle.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Labels: LGTM-will-merge-soon

#4357 Update documentation for example0 in RelBuilderExample
  core/src/test/java/org/apache/calcite/examples/RelBuilderExample.java
Labels: LGTM-will-merge-soon

#4365 Use StandardCharsets in RuleMatchVisualizer.java
  core/src/main/java/org/apache/calcite/plan/visualizer/RuleMatchVisualizer.java
Labels: LGTM-will-merge-soon

#4361 [CALCITE-7000] Extend IntersectToSemiJoinRule to support n-way inputs
  core/src/main/java/org/apache/calcite/rel/rules/IntersectToSemiJoinRule.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
  core/src/test/resources/sql/planner.iq
Labels: LGTM-will-merge-soon

#4368 [CALCITE-7006] Incorrect left join results with IS NOT DISTINCT FROM under specific plan
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/test/resources/sql/join.iq
Labels: LGTM-will-merge-soon

#4332 [CALCITE-6962] Exists subquery returns incorrect result when or condi…
  core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
  core/src/test/resources/sql/sub-query.iq
Labels: more-tests-needed

#4367 [CALCITE-7005] Invalid unparse for IS TRUE,IS FALSE,IS NOT TRUE and IS NOT FALSE in Hive/Presto Dialect
  core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
  core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Labels: LGTM-will-merge-soon

#4356 [CALCITE-6997] SQLite dialect implementation
  core/src/main/java/org/apache/calcite/sql/SqlDialect.java
  core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java
  core/src/main/java/org/apache/calcite/sql/dialect/SqliteSqlDialect.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
  core/src/test/java/org/apache/calcite/test/LintTest.java
Labels: LGTM-will-merge-soon

#4353 [CALCITE-6991] Validator cannot infer type for COALESCE when call is not expanded
  core/src/main/java/org/apache/calcite/sql/fun/SqlCaseOperator.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlCoalesceFunction.java
  core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercion.java
  core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercionImpl.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Labels: LGTM-will-merge-soon

#4374 [CALCITE-7013] Support building RexLiterals from Character values
  core/src/main/java/org/apache/calcite/rex/RexBuilder.java
  core/src/main/java/org/apache/calcite/tools/RelBuilder.java
  core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java
Labels: LGTM-will-merge-soon

#4358 [CALCITE-6998] The command !set planner-rules does not support rules with multiple Config
  core/src/main/java/org/apache/calcite/rel/rules/AggregateProjectPullUpConstantsRule.java
  core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
  core/src/main/java/org/apache/calcite/rel/rules/ExpandDisjunctionForJoinInputsRule.java
  core/src/main/java/org/apache/calcite/rel/rules/FilterJoinRule.java
  core/src/main/java/org/apache/calcite/rel/rules/FilterTableFunctionTransposeRule.java
  core/src/main/java/org/apache/calcite/rel/rules/JoinCommuteRule.java
  core/src/main/java/org/apache/calcite/rel/rules/JoinDeriveIsNotNullFilterRule.java
  core/src/main/java/org/apache/calcite/rel/rules/RuleConfig.java
  core/src/main/java/org/apache/calcite/rel/rules/SortUnionTransposeRule.java
  core/src/test/java/org/apache/calcite/test/LoadCoreRulesTest.java
  core/src/test/resources/sql/planner.iq
  testkit/src/main/java/org/apache/calcite/test/QuidemTest.java
Labels: LGTM-will-merge-soon

#4385 [CALCITE-7019] Simplify 'NULL IN (20, 10)' to 'NULL'
  core/src/main/java/org/apache/calcite/plan/Strong.java
  core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
Labels: LGTM-will-merge-soon

#4386 [CALCITE-6866] PostgreSQLDialect support to unparse LISTAGG aggregate function
  core/src/main/java/org/apache/calcite/sql/dialect/PostgresqlSqlDialect.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Labels: LGTM-will-merge-soon, needs-a-final-review

#4373 [CALCITE-7008] Extend MinusToAntiJoinRule to support n-way inputs
  core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
  core/src/main/java/org/apache/calcite/rel/rules/MinusToAntiJoinRule.java
  core/src/test/java/org/apache/calcite/test/JdbcTest.java
  core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
  core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
  core/src/test/resources/sql/planner.iq
Labels: LGTM-will-merge-soon

#4384 [CALCITE-6951] Add STRING_TO_ARRAY function(enabled in PostgreSQL Library)
  babel/src/test/resources/sql/postgresql.iq
  core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
  core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
  core/src/main/java/org/apache/calcite/sql/SqlKind.java
  core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
  core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
  site/_docs/reference.md
  testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Labels: LGTM-will-merge-soon, needs-a-final-review

#4355 [CALCITE-6978] Translation to relational algebra of correlated query with COALESCE causes an assertion failure
  core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
  core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
  core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
  core/src/test/resources/sql/sub-query.iq
Labels: LGTM-will-merge-soon

#4393 [CALCITE-7030] Enhance TopologicalOrderIterator to support BOTTOM_UP
  core/src/main/java/org/apache/calcite/plan/hep/HepPlanner.java
  core/src/main/java/org/apache/calcite/util/graph/DefaultDirectedGraph.java
  core/src/main/java/org/apache/calcite/util/graph/TopologicalOrderIterator.java
  core/src/test/java/org/apache/calcite/util/graph/DirectedGraphTest.java
Labels: LGTM-will-merge-soon

#4328 CALCITE-5638 Assertion Failure during planning correlated query with orderby
  core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
  core/src/main/java/org/apache/calcite/rel/rules/SubQueryRemoveRule.java
  core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java
  core/src/test/java/org/apache/calcite/test/enumerable/EnumerableCorrelateTest.java
  core/src/test/resources/sql/sub-query.iq
Labels: LGTM-will-merge-soon

#4389 [CALCITE-7027] Improve error message in case of several `UNION`, `INTERSECT`, `EXCEPT` in a query
  core/src/main/java/org/apache/calcite/sql/SqlUtil.java
  core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Labels: LGTM-will-merge-soon

#4395 [CALCITE-6952] JDBC adapter for StarRocks generates incorrect SQL for REAL datatype
  core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java
  core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Labels: LGTM-will-merge-soon

#4401 [CALCITE-7043] Type inferred for SqlItemOperator has incorrect nullability
  core/src/main/java/org/apache/calcite/sql/fun/SqlItemOperator.java
  core/src/test/java/org/apache/calcite/test/TableInRootSchemaTest.java
Labels: LGTM-will-merge-soon
